// Code generated by MockGen. DO NOT EDIT.
// Source: database.go

// Package aegis is a generated GoMock package.
package aegis

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	schemas "github.com/thecodearcher/aegis/schemas"
)

// MockDatabaseAdapter is a mock of DatabaseAdapter interface.
type MockDatabaseAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseAdapterMockRecorder
}

// MockDatabaseAdapterMockRecorder is the mock recorder for MockDatabaseAdapter.
type MockDatabaseAdapterMockRecorder struct {
	mock *MockDatabaseAdapter
}

// NewMockDatabaseAdapter creates a new mock instance.
func NewMockDatabaseAdapter(ctrl *gomock.Controller) *MockDatabaseAdapter {
	mock := &MockDatabaseAdapter{ctrl: ctrl}
	mock.recorder = &MockDatabaseAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseAdapter) EXPECT() *MockDatabaseAdapterMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockDatabaseAdapter) Count(ctx context.Context, tableName schemas.TableName, conditions []Where) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, tableName, conditions)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockDatabaseAdapterMockRecorder) Count(ctx, tableName, conditions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDatabaseAdapter)(nil).Count), ctx, tableName, conditions)
}

// Create mocks base method.
func (m *MockDatabaseAdapter) Create(ctx context.Context, tableName schemas.TableName, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tableName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDatabaseAdapterMockRecorder) Create(ctx, tableName, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDatabaseAdapter)(nil).Create), ctx, tableName, data)
}

// Delete mocks base method.
func (m *MockDatabaseAdapter) Delete(ctx context.Context, tableName schemas.TableName, conditions []Where) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tableName, conditions)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDatabaseAdapterMockRecorder) Delete(ctx, tableName, conditions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatabaseAdapter)(nil).Delete), ctx, tableName, conditions)
}

// Exists mocks base method.
func (m *MockDatabaseAdapter) Exists(ctx context.Context, tableName schemas.TableName, conditions []Where) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, tableName, conditions)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockDatabaseAdapterMockRecorder) Exists(ctx, tableName, conditions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDatabaseAdapter)(nil).Exists), ctx, tableName, conditions)
}

// FindMany mocks base method.
func (m *MockDatabaseAdapter) FindMany(ctx context.Context, tableName schemas.TableName, conditions []Where, options *QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, tableName, conditions, options)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockDatabaseAdapterMockRecorder) FindMany(ctx, tableName, conditions, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockDatabaseAdapter)(nil).FindMany), ctx, tableName, conditions, options)
}

// FindOne mocks base method.
func (m *MockDatabaseAdapter) FindOne(ctx context.Context, tableName schemas.TableName, conditions []Where, orderBy []OrderBy) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, tableName, conditions, orderBy)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockDatabaseAdapterMockRecorder) FindOne(ctx, tableName, conditions, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockDatabaseAdapter)(nil).FindOne), ctx, tableName, conditions, orderBy)
}

// Update mocks base method.
func (m *MockDatabaseAdapter) Update(ctx context.Context, tableName schemas.TableName, conditions []Where, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tableName, conditions, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDatabaseAdapterMockRecorder) Update(ctx, tableName, conditions, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDatabaseAdapter)(nil).Update), ctx, tableName, conditions, updates)
}

// MockDatabaseTx is a mock of DatabaseTx interface.
type MockDatabaseTx struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseTxMockRecorder
}

// MockDatabaseTxMockRecorder is the mock recorder for MockDatabaseTx.
type MockDatabaseTxMockRecorder struct {
	mock *MockDatabaseTx
}

// NewMockDatabaseTx creates a new mock instance.
func NewMockDatabaseTx(ctrl *gomock.Controller) *MockDatabaseTx {
	mock := &MockDatabaseTx{ctrl: ctrl}
	mock.recorder = &MockDatabaseTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseTx) EXPECT() *MockDatabaseTxMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockDatabaseTx) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockDatabaseTxMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDatabaseTx)(nil).Commit))
}

// Count mocks base method.
func (m *MockDatabaseTx) Count(ctx context.Context, tableName schemas.TableName, conditions []Where) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, tableName, conditions)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockDatabaseTxMockRecorder) Count(ctx, tableName, conditions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockDatabaseTx)(nil).Count), ctx, tableName, conditions)
}

// Create mocks base method.
func (m *MockDatabaseTx) Create(ctx context.Context, tableName schemas.TableName, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tableName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDatabaseTxMockRecorder) Create(ctx, tableName, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDatabaseTx)(nil).Create), ctx, tableName, data)
}

// Delete mocks base method.
func (m *MockDatabaseTx) Delete(ctx context.Context, tableName schemas.TableName, conditions []Where) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tableName, conditions)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDatabaseTxMockRecorder) Delete(ctx, tableName, conditions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDatabaseTx)(nil).Delete), ctx, tableName, conditions)
}

// Exists mocks base method.
func (m *MockDatabaseTx) Exists(ctx context.Context, tableName schemas.TableName, conditions []Where) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, tableName, conditions)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockDatabaseTxMockRecorder) Exists(ctx, tableName, conditions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDatabaseTx)(nil).Exists), ctx, tableName, conditions)
}

// FindMany mocks base method.
func (m *MockDatabaseTx) FindMany(ctx context.Context, tableName schemas.TableName, conditions []Where, options *QueryOptions) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMany", ctx, tableName, conditions, options)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMany indicates an expected call of FindMany.
func (mr *MockDatabaseTxMockRecorder) FindMany(ctx, tableName, conditions, options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMany", reflect.TypeOf((*MockDatabaseTx)(nil).FindMany), ctx, tableName, conditions, options)
}

// FindOne mocks base method.
func (m *MockDatabaseTx) FindOne(ctx context.Context, tableName schemas.TableName, conditions []Where, orderBy []OrderBy) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, tableName, conditions, orderBy)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockDatabaseTxMockRecorder) FindOne(ctx, tableName, conditions, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockDatabaseTx)(nil).FindOne), ctx, tableName, conditions, orderBy)
}

// Rollback mocks base method.
func (m *MockDatabaseTx) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockDatabaseTxMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockDatabaseTx)(nil).Rollback))
}

// Update mocks base method.
func (m *MockDatabaseTx) Update(ctx context.Context, tableName schemas.TableName, conditions []Where, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tableName, conditions, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDatabaseTxMockRecorder) Update(ctx, tableName, conditions, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDatabaseTx)(nil).Update), ctx, tableName, conditions, updates)
}
