package aegis

import (
	"context"
	"net/http"
	"time"
)

// this file contains the types for the aegis library
// NO FEATURES SHOULD BE ADDED TO THIS FILE those go in the feature.go file

type AegisSession struct {
	// User is the authenticated user
	User *User
	// Session is the validated session
	Session *Session
	// SessionExtensionResult is the result of a session extension operation
	// Only set if the session expiration was extended i.e UpdateAge is reached
	SessionExtensionResult *SessionExtensionResult
}

// AuthenticationResult represents the result of an authentication process and includes additional
type AuthenticationResult struct {
	// User represents the authenticated user
	User *User
	// Pending actions to be completed by the user before they can access the application e.g: two-factor authentication, email verification etc.
	PendingActions []PendingAction
}

// SessionCreateResult is returned by strategies
// Contains information needed by the session manager
type SessionCreateResult struct {
	Token          string          `json:"-"` // Token generated by strategy
	SessionValue   string          `json:"-"` // The value to be stored as the session in the database
	SessionOptions *SessionOptions `json:"-"` // Options for session storage (duration, metadata, etc.)
}

// Add SessionOptions struct (after SessionCreateOptions, around line 74)
type SessionOptions struct {
	// Duration for the session record in the database
	// If zero, uses the duration from SessionCreateOptions
	Duration time.Duration

	// Additional metadata to store with the session
	Metadata map[string]any
}

// SessionResult contains the result of session operations
type SessionResult struct {
	// Token is the session token
	Token string `json:"token,omitzero"`
	// Cookie is the cookie to be set for the session
	Cookie *http.Cookie `json:"-"`
	// TokenDeliveryMethod specifies how tokens should be delivered
	TokenDeliveryMethod TokenDeliveryMethod `json:"-"`
}

type SessionExtensionResult struct {
	// Token is the session token
	Token string

	// Cookie is the cookie to be set for the session
	Cookie *http.Cookie `json:"-"`
}

type SessionValidateResult struct {
	AegisSession
	// UserID is the ID of the authenticated user
	UserID any
}

// SessionCreateOptions contains options for creating a session
type SessionCreateOptions struct {
	// Duration for the session/token
	Duration time.Duration

	// TemporaryAuth indicates if this is a temporary auth session (e.g., 2FA, email verification)
	TemporaryAuth bool
}

// SessionStore defines the interface for session storage backends
type SessionStore interface {
	// Create creates a new session with the given ID and data
	Create(ctx context.Context, session *Session) error

	// Get retrieves a session by token
	Get(ctx context.Context, sessionToken string) (*Session, error)

	// Update updates an existing session
	Update(ctx context.Context, id any, session *Session) error

	// Delete removes a session by token
	Delete(ctx context.Context, sessionToken string) error

	// DeleteByUserID removes all sessions for a specific user
	DeleteByUserID(ctx context.Context, userID any) error
}

// SessionStrategy defines the interface for different session management strategies
type SessionStrategy interface {
	// Create creates a new session for the given user
	Create(ctx context.Context, user *User, options *SessionCreateOptions) (*SessionCreateResult, error)

	// Validate validates a session from the request
	Validate(ctx context.Context, request *http.Request) (*SessionValidateResult, error)

	// GetName returns the strategy name
	GetName() string

	// IsStateful returns whether the strategy is stateful
	IsStateful() bool

	// SupportsExpirationExtension returns whether the strategy supports
	// extending session expiration time on use (sliding window behavior).
	// Only applies to stateful strategies where expiration can be modified.
	SupportsExpirationExtension() bool
}
