package twofactor

import (
	"context"
	"net/http"

	"github.com/thecodearcher/aegis"
	credentialpassword "github.com/thecodearcher/aegis/features/credential-password"
)

// InitiateTwoFactorSetup initiates the 2FA setup process
func (t *twoFactorFeature) InitiateTwoFactorSetup(ctx context.Context, user *UserWithTwoFactor, password string) (*TwoFactorSetupURI, error) {
	if user.TwoFactorEnabled {
		return nil, ErrTwoFactorAlreadyEnabled
	}

	if err := t.checkPassword(user.User, password); err != nil {
		return nil, err
	}

	// secret is empty because it is generated by the totp library
	result, err := t.totp.GenerateSetupURI(user.Email, "")
	if err != nil {
		return nil, err
	}

	backupCodes := t.backupCodes.GenerateBackupCodes()
	encryptedBackupCodes, err := t.backupCodes.encryptBackupCodes(backupCodes)
	if err != nil {
		return nil, err
	}

	encryptedSecret, err := t.encrypt(result.Secret)
	if err != nil {
		return nil, err
	}

	if err := t.DeleteTwoFactor(ctx, user.ID); err != nil {
		return nil, err
	}

	if err := t.CreateTwoFactor(ctx, user.ID, encryptedSecret, encryptedBackupCodes); err != nil {
		return nil, err
	}

	return result, nil
}

// FinalizeTwoFactorSetup finalizes the 2FA setup process
// It verifies the provided code and enables 2FA for the user
func (t *twoFactorFeature) FinalizeTwoFactorSetup(ctx context.Context, user *UserWithTwoFactor, code string) error {
	if user.TwoFactorEnabled {
		return ErrTwoFactorAlreadyEnabled
	}

	if err := t.totp.VerifyCode(ctx, user.ID, code); err != nil {
		return err
	}

	updatedUser := &UserWithTwoFactor{TwoFactorEnabled: true}
	if err := t.core.Update(ctx, t.userSchema, updatedUser, []aegis.Where{
		aegis.Eq(t.userSchema.GetIDField(), user.ID),
	}); err != nil {
		return err
	}

	return nil
}

// DisableTwoFactor disables 2FA for a user
func (t *twoFactorFeature) DisableTwoFactor(ctx context.Context, userID any, password string) error {
	user, err := t.core.DBAction.FindUserByID(ctx, userID)
	if err != nil {
		return err
	}

	if err = t.checkPassword(user, password); err != nil {
		return err
	}

	return t.core.WithTransaction(ctx, func(ctx context.Context) error {
		if err := t.DeleteTwoFactor(ctx, userID); err != nil {
			return err
		}

		updatedUser := &UserWithTwoFactor{TwoFactorEnabled: false}

		return t.core.UpdateRaw(ctx, t.userSchema, updatedUser, []aegis.Where{
			aegis.Eq(t.userSchema.GetIDField(), userID),
		}, false)
	})
}

func (t *twoFactorFeature) checkPassword(user *aegis.User, password string) error {
	feature, ok := t.core.GetFeature(aegis.FeatureCredentialPassword)
	if !ok {
		return ErrCredentialPasswordFeatureNotAvailable
	}
	credentialPasswordAPI := feature.(credentialpassword.API)

	isValid, err := credentialPasswordAPI.ComparePassword(password, user.Password)
	if err != nil {
		return err
	}
	if !isValid {
		return ErrInvalidPassword
	}

	return nil
}

// VerifyLoginWithTwoFactor verifies the 2FA code and completes the login process
func (t *twoFactorFeature) VerifyLoginWithTwoFactor(r *http.Request, w http.ResponseWriter, code string, method TwoFactorMethod) (*aegis.AuthenticationResult, *aegis.SessionResult, error) {
	challengeToken, err := t.getChallengeFromCookie(r)
	if err != nil {
		return nil, nil, err
	}

	challenge, err := t.verifyChallengeToken(challengeToken)
	if err != nil {
		return nil, nil, err
	}

	if err := t.verifyLoginCode(r.Context(), challenge.UserID, code, method); err != nil {
		return nil, nil, err
	}

	t.clearChallengeCookie(w)

	user, err := t.core.DBAction.FindUserByID(r.Context(), challenge.UserID)
	if err != nil {
		return nil, nil, err
	}

	authResult := &aegis.AuthenticationResult{User: user}
	sessionResult, err := t.core.SessionManager.CreateSession(r.Context(), r, authResult)
	if err != nil {
		return nil, nil, err
	}
	return authResult, sessionResult, nil
}

// verifyLoginCode verifies the login code and returns an error if the code is invalid
// It supports TOTP, OTP, and backup codes
func (t *twoFactorFeature) verifyLoginCode(ctx context.Context, userID any, code string, method TwoFactorMethod) error {
	if looksLikeBackupCode(code) {
		return t.backupCodes.VerifyBackupCode(ctx, userID, code)
	}

	switch method {
	case TwoFactorMethodTOTP:
		return t.totp.VerifyCode(ctx, userID, code)
	case TwoFactorMethodOTP:
		if t.otp == nil {
			return ErrInvalidCode
		}
		return t.otp.Verify(ctx, userID, code)
	}
	return ErrInvalidCode
}
