package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/urfave/cli/v3"
)

const (
	defaultOutputPath     = "./models"
	defaultSchemasPath    = "./.aegis/schemas.json"
	defaultMigrationsPath = "./migrations"
)

func main() {
	app := &cli.Command{
		Name:  "aegis",
		Usage: "Aegis CLI Tool",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "schemas",
				Aliases: []string{"s"},
				Usage:   "Path to schemas file generated by aegis",
				Value:   defaultSchemasPath,
			},
		},
		Commands: []*cli.Command{
			{
				Name:  "generate",
				Usage: "Generate Go structs from schemas",
				Commands: []*cli.Command{
					{
						Name:  "models",
						Usage: "Generate models from schemas",
						Flags: []cli.Flag{
							&cli.StringFlag{
								Name:    "output",
								Aliases: []string{"o"},
								Usage:   "Output directory for generated structs",
								Value:   defaultOutputPath,
							},
							&cli.StringFlag{
								Name:    "package",
								Aliases: []string{"p"},
								Usage:   "Package name for generated code",
							},
						},
						Action: runGenerateModels,
					},
					{
						Name:  "migrations",
						Usage: "Generate migration files from schemas",
						Flags: []cli.Flag{
							&cli.StringFlag{
								Name:    "output",
								Aliases: []string{"o"},
								Usage:   "Output directory for generated migrations",
								Value:   defaultMigrationsPath,
							},
							&cli.StringFlag{
								Name:     "driver",
								Aliases:  []string{"d"},
								Usage:    "Database driver name (postgres, mysql) - used for SQL generation",
								Required: true,
							},
							&cli.StringFlag{
								Name:     "dsn",
								Usage:    "Database connection string for introspection",
								Aliases:  []string{"c"},
								Required: true,
							},
						},
						Action: runMigrateGenerate,
					},
				},
			},
		},
	}

	if err := app.Run(context.Background(), os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func runGenerateModels(ctx context.Context, cmd *cli.Command) error {
	schemasPath := cmd.String("schemas")
	outputPath := cmd.String("output")
	packageName := cmd.String("package")

	schemas, err := loadSchemaFromConfig(schemasPath)
	if err != nil {
		return err
	}

	if packageName == "" {
		packageName = strings.ToLower(filepath.Base(outputPath))
	}

	code := GenerateGoStructs(schemas, GenerateOptions{
		PackageName: packageName,
		Tags:        []string{"json"},
		FieldNaming: strcase.ToCamel,
	})

	outputFile := filepath.Join(outputPath, "models.go")
	if err := os.MkdirAll(filepath.Dir(outputFile), 0755); err != nil {
		return fmt.Errorf("error creating output directory: %w", err)
	}

	if err := os.WriteFile(outputFile, []byte(code), 0644); err != nil {
		return fmt.Errorf("error writing output file: %w", err)
	}

	fmt.Printf("Generated structs written to %s\n", outputFile)
	return nil
}

func runMigrateGenerate(ctx context.Context, cmd *cli.Command) error {
	schemasPath := cmd.String("schemas")
	outputPath := cmd.String("output")
	driverName := cmd.String("driver")
	dsn := cmd.String("dsn")

	config, err := loadConfig(schemasPath)
	if err != nil {
		return fmt.Errorf("error loading config: %w", err)
	}

	driver, err := GetDriversRegistry().getDriver(driverName)
	if err != nil {
		return fmt.Errorf("error getting driver: %w", err)
	}

	if dsn == "" {
		return fmt.Errorf("dsn is required")
	}

	var migrations []Migration

	db, err := driver.Connect(dsn)
	if err != nil {
		return fmt.Errorf("error connecting to database: %w", err)
	}

	migrations, err = generateMigrations(db, driver, config)
	if err != nil {
		return fmt.Errorf("error generating migrations: %w", err)
	}

	if err := os.MkdirAll(outputPath, 0755); err != nil {
		return fmt.Errorf("error creating output directory: %w", err)
	}

	for _, migration := range migrations {
		if migration.UpSQL == "" {
			continue
		}

		upFile := filepath.Join(outputPath, fmt.Sprintf("%s.up.sql", migration.Version))
		downFile := filepath.Join(outputPath, fmt.Sprintf("%s.down.sql", migration.Version))

		if err := os.WriteFile(upFile, []byte(migration.UpSQL), 0644); err != nil {
			return fmt.Errorf("error writing migration file: %w", err)
		}

		if err := os.WriteFile(downFile, []byte(migration.DownSQL), 0644); err != nil {
			return fmt.Errorf("error writing migration file: %w", err)
		}

		fmt.Printf("Generated migration: %s\n", migration.Version)
	}

	fmt.Println("\nTo apply these migrations, use any other migration tool that supports SQL files like goose, golang-migrate, etc. Or apply them manually.")

	return nil
}
