package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/urfave/cli/v3"
)

const (
	defaultOutputPath  = "./models"
	defaultSchemasPath = "./.aegis/schemas.json"
)

func main() {
	app := &cli.Command{
		Name:  "aegis",
		Usage: "Aegis CLI Tool",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:    "schemas",
				Aliases: []string{"s"},
				Usage:   "Path to schemas file generated by aegis",
				Value:   defaultSchemasPath,
			},
		},
		Commands: []*cli.Command{
			{
				Name:  "introspect",
				Usage: "Generate Go structs from schemas",
				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:    "output",
						Aliases: []string{"o"},
						Usage:   "Output directory for generated structs",
						Value:   defaultOutputPath,
					},
					&cli.StringFlag{
						Name:    "package",
						Aliases: []string{"p"},
						Usage:   "Package name for generated code",
					},
				},
				Action: runIntrospect,
			},
			{
				Name:  "migrate",
				Usage: "Database migration commands",
				Commands: []*cli.Command{
					{
						Name:  "generate",
						Usage: "Generate migration files",
						Flags: []cli.Flag{
							&cli.StringFlag{
								Name:    "output",
								Aliases: []string{"o"},
								Usage:   "Output directory for migration files",
								Value:   "./migrations",
							},
							&cli.StringFlag{
								Name:    "driver",
								Aliases: []string{"d"},
								Usage:   "Database driver name (postgres, mysql) - used for SQL generation",
								Value:   string(DriverPostgres),
							},
							&cli.StringFlag{
								Name:    "dsn",
								Usage:   "Database connection string for introspection",
								Aliases: []string{"c"},
							},
						},
						Action: runMigrateGenerate,
					},
					{
						Name:  "up",
						Usage: "Apply pending migrations",
						Flags: []cli.Flag{
							&cli.StringFlag{
								Name:     "config",
								Aliases:  []string{"c"},
								Usage:    "Path to Go file containing Config struct",
								Required: true,
							},
							&cli.StringFlag{
								Name:  "dsn",
								Usage: "Database connection string (overrides config)",
								Value: "",
							},
							&cli.StringFlag{
								Name:    "driver",
								Aliases: []string{"d"},
								Usage:   "Database driver name (postgres, mysql) - used for SQL generation and connection",
								Value:   string(DriverPostgres),
							},
						},
						Action: runMigrateUp,
					},
					{
						Name:   "down",
						Usage:  "Rollback last migration",
						Action: runMigrateDown,
					},
					{
						Name:   "status",
						Usage:  "Show migration status",
						Action: runMigrateStatus,
					},
				},
			},
		},
	}

	if err := app.Run(context.Background(), os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func runIntrospect(ctx context.Context, cmd *cli.Command) error {
	schemasPath := cmd.String("schemas")
	outputPath := cmd.String("output")
	packageName := cmd.String("package")

	schemas, err := loadSchemaFromConfig(schemasPath)
	if err != nil {
		return err
	}

	if packageName == "" {
		packageName = strings.ToLower(filepath.Base(outputPath))
	}

	code := GenerateGoStructs(schemas, GenerateOptions{
		PackageName: packageName,
		Tags:        []string{"json"},
		FieldNaming: defaultFieldNaming,
	})

	outputFile := filepath.Join(outputPath, "models.go")
	if err := writeFile(outputFile, []byte(code)); err != nil {
		return fmt.Errorf("error writing output file: %w", err)
	}

	fmt.Printf("Generated structs written to %s\n", outputFile)
	return nil
}

func runMigrateGenerate(ctx context.Context, cmd *cli.Command) error {
	schemasPath := cmd.String("schemas")
	outputPath := cmd.String("output")
	driverName := cmd.String("driver")
	dsn := cmd.String("dsn")

	config, err := loadConfig(schemasPath)
	if err != nil {
		return fmt.Errorf("error loading config: %w", err)
	}

	driver, err := GetDriversRegistry().getDriver(driverName)
	if err != nil {
		return fmt.Errorf("error getting driver: %w", err)
	}

	if dsn == "" {
		return fmt.Errorf("dsn is required")
	}

	var migrations []Migration

	db, err := driver.Connect(dsn)
	if err != nil {
		return fmt.Errorf("error connecting to database: %w", err)
	}

	migrations, err = generateMigrations(db, driver, config)
	if err != nil {
		return fmt.Errorf("error generating migrations: %w", err)
	}

	// Write migration files
	if err := os.MkdirAll(outputPath, 0755); err != nil {
		return fmt.Errorf("error creating output directory: %w", err)
	}

	for _, migration := range migrations {
		// Skip empty migrations
		if migration.UpSQL == "" {
			continue
		}

		upFile := filepath.Join(outputPath, fmt.Sprintf("%s.up.sql", migration.Version))
		downFile := filepath.Join(outputPath, fmt.Sprintf("%s.down.sql", migration.Version))

		if err := os.WriteFile(upFile, []byte(migration.UpSQL), 0644); err != nil {
			return fmt.Errorf("error writing migration file: %w", err)
		}

		if err := os.WriteFile(downFile, []byte(migration.DownSQL), 0644); err != nil {
			return fmt.Errorf("error writing migration file: %w", err)
		}

		fmt.Printf("Generated migration: %s\n", migration.Version)
	}

	return nil
}

func runMigrateUp(ctx context.Context, cmd *cli.Command) error {
	// configPath := cmd.String("config")
	// dsn := cmd.String("dsn")
	// driver := cmd.String("driver")

	// Load config and schemas from file
	// schemas, err := loadSchemaFromFile(configPath)
	// if err != nil {
	// 	return fmt.Errorf("error loading config: %w", err)
	// }

	// // Connect to database
	// db, err := connectDatabase(driver, dsn)
	// if err != nil {
	// 	return fmt.Errorf("error connecting to database: %w", err)
	// }

	// adapter := gormadapter.New(db)
	// applier := &gormMigrationApplier{adapter: adapter, db: db}

	// // Generate migrations directly from schemas
	// generator := newSQLMigrationGenerator(driver, config)
	// migrations, err := generateMigrationsFromSchemas(schemas, generator)
	// if err != nil {
	// 	return fmt.Errorf("error generating migrations: %w", err)
	// }

	// Apply migrations
	// if err := aegis.ApplyMigrations(ctx, config, migrations, applier); err != nil {
	// 	return fmt.Errorf("error applying migrations: %w", err)
	// }

	fmt.Println("Migrations applied successfully")
	return nil
}

func runMigrateDown(ctx context.Context, cmd *cli.Command) error {
	return fmt.Errorf("migrate down is not yet implemented")
}

func runMigrateStatus(ctx context.Context, cmd *cli.Command) error {
	return fmt.Errorf("migrate status is not yet implemented")
}

func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("error creating output directory: %w", err)
	}

	return os.WriteFile(path, content, 0644)
}
